### PR TITLE
Fix relative require() path in Windows

### LINKED ISSUE #55: Possible regression caused by switch to relative paths
There was a lot of activity on strongloop/strong-mesh-client#40 starting just 10 hours after v6.6.1 was released.

Given that all the reports have been on Windows and I haven't been able to reproduce the problem on Mac or Linux, I'm beginning to suspect #54 introduced a Windows specific regression.

### PR DESCRIPTION
**Pull request by parshap**
Introduced in #54. Fixes #55.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -7,8 +7,8 @@ var processPath = require.resolve('process/browser.js');
 var isbufferPath = require.resolve('is-buffer')
 var combineSourceMap = require('combine-source-map');
 
-function getRelativePath(fullPath, fromPath) {
-  var relpath = path.relative(path.dirname(fromPath), fullPath);
+function getRelativeRequirePath(fullPath, fromPath) {
+  var relpath = path.posix.relative(path.dirname(fromPath), fullPath);
```
Comment (rmg) [inline index.js]: `path.posix` was only introduced in node-v0.11.15, so this needs a fallback or to use a shimmed version of `path` like path-posix or similar.

Comment (rmg) [inline index.js]: Disregard, I see #57 and #58 have already been opened for this.

**Comment by parshap** [comment]
@nnarhinen: This was an incompatibility with 0.10. A fix is now released in `insert-module-globals@6.6.3`.
